[[redirects]]
  from = "/400"
  to = "/400.html"
  status = 400

[[redirects]]
  from = "/401"
  to = "/401.html"
  status = 401

[[redirects]]
  from = "/403"
  to = "/403.html"
  status = 403

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500"
  to = "/500.html"
  status = 500

[[redirects]]
  from = "/503"
  to = "/503.html"
  status = 503

  [[redirects]]
  from = "/504"
  to = "/504.html"
  status = 504

[[redirects]]
  from = "/*"
  to = "/503.html"
  status = 503

